version: "3.7"
services:
   mongo:    
    image: mongo:4.2-bionic
    ports:
        - "28017:27017"
    volumes: 
        - mongo.data:/data/db
    environment: 
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: VeryStrongPass@             
volumes: 
    mongo.data:
