@baseUrl=http://localhost:32000


### login root test
# @name loginRoot
POST {{baseUrl}}/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "toor"
}


@authToken = {{loginRoot.response.body.$.token}}
# changed signature
###

###
GET {{baseUrl}}/api/user/root
Authorization: Bearer {{authToken}}

### Login Admin

POST {{baseUrl}}/api/login
Content-Type: application/json

{
    "username": "superadmin",
    "password": "superadmin"
}


### Wrong Password Root

POST {{baseUrl}}/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "wrong-password"
}

### Get user from context
GET {{baseUrl}}/api/current
Authorization: Bearer {{authToken}}